--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/cosmicnebula200/FunBlockOneBlock
build-by-default: true
branches:
- main
projects:
  FunBlockOneBlock:
    path: ""
    libs:
      - src: CortexPE/Commando/Commando
        version:  ^3.0.0
        branch: PM4
...
