name: FunBlockOneBlock
api: 4.0.0
author: cosmicnebula200
main: cosmicnebula200\FunBlockOneBlock\FunBlockOneBlock
version: 1.0.0

permissions:
  funblockoneblock.command:
    default: true
    description: this permission allows the set user to use the oneblock command
  funblockoneblock.create:
    default: true
    description: this permission allows the user to create a OneBlock Island
  funblockoneblock.delete:
    default: true
    description: with this permission the user can delete their island
  funblockoneblock.deleteothers:
    default: op
    description: with this permission the user can delete other players one islands
  funblockoneblock.go:
    default: true
    description: this permission allows the user to teleport to the oneblock island
  funblockoneblock.invite:
    default: true
    description: this permission allows the user to invite players to their oneblock island
  funblockoneblock.accept:
    default: true
    description: this permission allows the user to accept incoming invites when they have no oneblock island