name: FunBlockOneBlock
api: 4.0.0
author: cosmicnebula200
main: cosmicnebula200\FunBlockOneBlock\FunBlockOneBlock
version: 1.0.0-BETA-1

permissions:
  funblockoneblock.command:
    default: true
    description: this permission allows the set user to use the oneblock command
  funblockoneblock.create:
    default: true
    description: this permission allows the user to create a oneblock island
  funblockoneblock.chat:
    default: true
    description: this permission allows the user to use the oneblock chat
  funblockoneblock.delete:
    default: true
    description: with this permission the user can delete their oneblock island
  funblockoneblock.deleteothers:
    default: op
    description: with this permission the user can delete other players oneblock islands
  funblockoneblock.go:
    default: true
    description: this permission allows the user to teleport to the oneblock island
  funblockoneblock.visit:
    default: true
    description: this permission allows the user to visit other players oneblock islands
  funblockoneblock.invite:
    default: true
    description: this permission allows the user to invite players to their oneblock island
  funblockoneblock.accept:
    default: true
    description: this permission allows the user to accept incoming invites when they have no oneblock island