# Config for FunBlockOneBlock by cosmicnebula200
database:
  # The database type. "sqlite" and "mysql" are supported.
  type: sqlite

  # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
    # You can also put an absolute path here.
    file: oneblock.sql

  # Edit these settings only if you choose "mysql".
  mysql:
    host: 127.0.0.1
    # Avoid using the "root" user for security reasons.
    username: root
    password: ""
    schema: oneblock
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 1


# Enable this only if you have FunBlockLuckyBlock installed on your servers
luckyblocks:
  enabled: false
  chance: 1

# See README.md for more information about each individual setting
settings:
  autoinv:
    enabled: true
    drop-when-full: true
  autoxp: true
  invite-timeout: 30
  max-members: 5
  reset-xp: true
  damage:
    player: false
    lava: true
    drown: true
    fall: false
    projectile: false
    fire: true
    void: false
    hunger: true